name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        model_type: [ fast-fp8, fast-bf16, dev-fp8, dev-bf16 ]

    steps:
      # 1. Kaynak kodu çek
      - uses: actions/checkout@v4

      # 2. Docker Hub’a login ol
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3. Build & push
      - name: Build and push ${{ matrix.model_type }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            MODEL_TYPE=${{ matrix.model_type }}
          tags: |
            aykutmursalo/hidream-inference:${{ matrix.model_type }}
