name: Release
on:
  workflow_dispatch:
    inputs:
      model_type:
        description: 'Which model to build & push'
        required: true
        default: 'fast-fp8'
        type: choice
        options:
          - fast-fp8
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    steps:
    # =============  INITIAL DISK SPACE CHECK  =============
    - name: Check initial disk space
      run: df -h
      
    # =============  AGGRESSIVE DISK CLEANUP  =============
    - name: Free up disk space (aggressive cleanup)
      run: |
        echo "Starting aggressive disk cleanup..."
        # Remove large unused directories
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf "/usr/local/share/boost"
        
        # Clean Docker images and build cache
        sudo docker image prune --all --force
        sudo docker builder prune --all --force
        
        # Clean package managers and temporary files
        sudo apt-get clean
        sudo apt-get autoremove -y
        sudo rm -rf /var/lib/apt/lists/*
        
        echo "Cleanup completed."
        
    - name: Check disk space after cleanup
      run: df -h

    # =============  SETUP  =============
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    # README varsa ToC güncelle; yoksa atla
    - name: Update the ToC in the README.md
      if: hashFiles('README.md') != ''
      run: |
        npm install -g markdown-toc
        markdown-toc README.md -i
    
    # =============  SEMANTIC-RELEASE (yalnız push) =============
    - name: Install semantic-release packages
      if: github.event_name == 'push'
      run: |
        npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
    
    - name: Run Semantic Release
      if: github.event_name == 'push'
      id: semantic_release
      run: |
        RELEASE_VERSION=$(npx semantic-release --dry-run | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+' || echo "1.0.0")
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
        echo "release-version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
        
        # Only run the actual release if we're not in dry-run
        if [[ "${{ github.event_name }}" == "push" ]]; then
          npx semantic-release
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # =============  ENV VARS =============
    - name: Set environment variables
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      run: |
        echo "DOCKERHUB_REPO=${{ vars.DOCKERHUB_REPO || 'aykutmursalo' }}" >> $GITHUB_ENV
        echo "DOCKERHUB_IMG=${{ vars.DOCKERHUB_IMG || 'hidream-inference-fast-fp8' }}" >> $GITHUB_ENV
        echo "HUGGINGFACE_ACCESS_TOKEN=${{ secrets.HUGGINGFACE_ACCESS_TOKEN }}" >> $GITHUB_ENV
        echo "RELEASE_VERSION=${RELEASE_VERSION:-1.0.0}" >> $GITHUB_ENV
    
    # Check disk space before build
    - name: Check disk space before build
      run: df -h
      
    # =============  BUILD & PUSH  =============
    - name: Build and push the fast-fp8 image
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      uses: docker/bake-action@v2
      with:
        push: true
        targets: "fast-fp8"
        set: |
          fast-fp8.tags=${{ env.DOCKERHUB_REPO }}/${{ env.DOCKERHUB_IMG }}:${{ env.RELEASE_VERSION }}-fast-fp8
          fast-fp8.args.DOCKERHUB_REPO=${{ env.DOCKERHUB_REPO }}
          fast-fp8.args.DOCKERHUB_IMG=${{ env.DOCKERHUB_IMG }}
          fast-fp8.args.RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          fast-fp8.args.HUGGINGFACE_ACCESS_TOKEN=${{ env.HUGGINGFACE_ACCESS_TOKEN }}
    
    # Final disk space check
    - name: Check final disk space
      run: df -h